# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    Quotes: /quotes
    About: /about

# Customize
customize:
    logo:
        width: 165
        height: 80
        url: ../images/logo.png
    theme_color: '#d35'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: images/vincent.ico
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        facebook-official: https://www.facebook.com/twang443
        linkedin-square: https://www.linkedin.com/in/twang443
        twitter: https://twitter.com/twang443
        instagram: https://www.instagram.com/twang443
        github: https://github.com/TingSyuanWang

# Widgets
widgets:
    - catalog
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links
#    - google_adsense

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: #vincents-corner #enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: true # enter true to enable
    valine: # Valine Comment System https://github.com/xCss/Valine
        on: # enter true to enable valine
        appId:  # enter the leancloud application appId here
        appKey:  # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier>, default: false; https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>, default: false
        placeholder: Just Do It # enter the comment box placeholder
        avatar: identicon # (''/mm/identicon/monsterid/wavatar/retro/hide), more to see https://valine.js.org/avatar.html
        avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.cat.net
        pageSize: 10 # comments of one page
        visitor: true # count reading numbers; If true, the numbers will also show below the title of every post
        recordip: #false # If true, record commenter's ip, which is shown in LeanCloud pannel

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: UA-84065024-1 # enter the tracking ID for your Google Analytics
    google_adsense:
      publisher_id: # enter the adsense publisher ID (pub-XXXXXXXXXXXXXXX) for your google adsense
      ad_slot: # the id of your add unit
    baidu_analytics: # enter Baidu Analytics hash key
    bing_site_verification: # enter Bing verification key here
    statcounter:
      sc_project: # enter statcounter project id
      sc_invisible: # enter 1 to make statcounter invisible
      sc_security: # enter security code
      public: # enter true if you want a link to your public stats. Must be configured on statcouter as well.
      on: # enter true to enable statcounter
    mathjax: true # options: true, false
    counter: true # for post words count and time of reading, need hexo-wordcount: https://github.com/willin/hexo-wordcount
    cookie_consent: false
    twitter_conversion_tracking:
      enabled: false
      pixel_id: ''

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id: 1958612367696881
        fb_admins: 'VincentTingSyuanWang'
        twitter_id:
    links:
        Facebook: https://www.facebook.com/VincentTingSyuanWang
        最優雅的搜尋引擎-卡拉搜索: https://kalasearch.cn

poweredby: true
